---

postgres_ha_service_name: 'nim-waku-db'
postgres_ha_cont_image: 'postgres:15.1-alpine'

postgres_ha_is_master: true
postgres_ha_replica_enabled: false
postgres_ha_replica_allowed_addresses: []

postgres_ha_admin_user: 'postgres'
postgres_ha_admin_pass: '{{lookup("bitwarden", "fleets/waku/"+stage+"/db/admin")}}'

postgres_ha_databases:
  - name: 'nim-waku'
    user: 'nim-waku'
    pass: '{{lookup("bitwarden", "fleets/waku/"+stage+"/db/nim-waku")}}'

postgres_ha_backup: false

# Open PostgreSQL Port
open_ports_default_comment: '{{ postgres_ha_service_name }}'
open_ports_list:
   postgres: 
    - { port: '{{ postgres_ha_cont_port }}', ipset: '{{ env }}.{{ stage }}', iifname: 'wg0' }
