- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git

- name: infra-role-open-ports
  src: git@github.com:status-im/infra-role-open-ports.git

- name: infra-role-swap-file
  src: git@github.com:status-im/infra-role-swap-file.git

- name: infra-role-consul-service
  src: git@github.com:status-im/infra-role-consul-service.git

- name: infra-role-systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git

- name: infra-role-certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: 8b5f4ed137e399a33c10b7ffbeaacb6e0c52fcb1

- name: infra-role-nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: b11d280d456d6010bf92a05356f2140ac0983a2f

- name: infra-role-postgres-ha
  src: git@github.com:status-im/infra-role-postgres-ha.git
  version: 39efd317a8f4b4c3d553f19cf3dbd9d98f451b0e

- name: infra-role-wazuh-agent
  src: git@github.com:status-im/infra-role-wazuh-agent.git
  version: ed4f5ac1e816b435ffe3e6c236586823c0e5ff30
